name: MangoQuest
main: me.Cutiemango.MangoQuest.Main
version: 1.9.8
api-version: 1.13
authors: [Cutiemango]
depend: [Vault, Citizens]
softdepend: [MythicMobs, SkillAPI, QuantumRPG, Shopkeepers]
commands:
   mq:
      description: Main command for MangoQuest
   mqa:
      description: Admin command for MangoQuest